version: '3'

services:
  api:
    build: ./api
    ports:
        - 80:80
    depends_on:
        - php
    volumes:
        - ./api:/var/www/html/api
        - ./api/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

  php:
    build: ./php
    depends_on:
        - db
    links:
        - db
    volumes:
        - ./api:/var/www/html/api
        - ./php/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql:5.7.19
    ports:
      - ${MYSQL_PORT}:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - "./db:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./initdata:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_PORT=${MYSQL_PORT}
    depends_on:
      - db
    ports:
      - 8081:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"

